### ISSUE TITLE
Delay issue and/or socat kills cec-client

### ISSUE THREAD

**Issue by robbiet480** [jasmas/cecd#1]
Hey @jasmas,

Do you have a 3 second delay between socat receiving a command and it being executed? I can tell the delay is in cec-client starting up. Trying to figure out if there is a way to fix this OR if there is a way to fix socat killing cec-client after a period of inactivity. [I wrote a bit more about this issue on ServerFault](https://serverfault.com/questions/655715/always-keep-socat-alive)

Thanks!

**Comment by jasmas** [comment]
Did you change the default options passed to cec-client in the script?

**Comment by robbiet480** [comment]
@jasmas Just changed case and manually set the path to cec-client. The exact command i've been using is `socat tcp-listen:2600,reuseaddr,fork exec:"/usr/bin/cec-client $CEC_CLIENT_ARGS"`. In the README.md on my fork, I wrote a little 3 line bash script which puts a pty between the tcp and cec-client so that cec-client always stays online and removes the startup delay.

**Comment by jasmas** [comment]
I'm talking about the switches for cec-client not socat. You need to put cec-client in monitor mode on start-up to avoid the delay. I just realized I didn't include my config files in the project, I'll have to upload them.

**Comment by jasmas** [comment]
The reason I was starting a client with each connection was to better handle multiple, simultaneous connections.

**Comment by robbiet480** [comment]
@jasmas Hey `-m` works great! Wish I had known about that a few days ago, but just happy now that it doesn't need such a hack solution. There is a minor delay still but it's much better than before. It would still be great to see your CEC config files. 

I'm still working on writing a daemon of sorts specifically for Roomie to provide feedback for volume/channel/input and with some bells & whistles like Avahi/Bonjour support so Roomie can auto detect, the ability to target devices other than TVs, like BluRay players and the like and support for more Roomie commands like .CHANNEL SET. It would also (hopefully) avoid the delay issue and be cleaner than socat is currently (IMHO). I think that CEC control is by far a better and cheaper solution then purchasing an adapter (although I already have one) because of the feedback possibilities. All of my work is going to end up in my fork, or another project. 

Thanks for your work & help so far!

**Comment by jasmas** [comment]
@robbiet480 Be sure to let me know of your project once you start it, I may be interested in helping out. cec-client itself is meant as an example implementation of libCEC. You may want to review the source as a start.

I've updated the repository with an example cecd.conf that should help users avoid the snag you ran into. Thank-you for pointing out the omission.
